name: hubert-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - azure-ai-ml>=1.12.0
      - azure-identity>=1.14.0
      - torch>=2.0.0
      - soundfile>=0.12.0
      - numpy>=1.24.0
      - transformers>=4.35.0
      - librosa>=0.10.0
      - azureml-inference-server-http
      - protobuf>=3.20.0
